---
language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11
  - openjdk8

env:
  - PYTHON=python3

matrix:
  fast_finish: true

before_install:
  - python3 --version
  - pip install --user -r requirements.txt

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dpython="$PYTHON"

script:
  - mvn test -B -Dpython="$PYTHON"
